### ISSUE TITLE
Make EMS-ESP work as a real thermostat

### ISSUE THREAD

**Issue by moustic999** [proddy/EMS-ESP#539] opened 2020-10-08 09:13 UTC
It would be great to have The possibility for EMS-ESP to act as a real thermostat within the Heating system.

Today the EMS-ESP is detected as a Service Key.

That would allow to build similar feature than a  TADO thermostat ourself.

In order to achieve this, we should change from service key Id to thermostat Id and probably have some message exchange on the bus to validate this thermostat.

**Comment by proddy** [comment] 2020-10-08 09:15
This gets discussed a lot ! It's a duplicate of https://github.com/proddy/EMS-ESP/issues/524

Feel free to re-open and comment.

Closing.

**Closed by proddy** 2020-10-08 09:15 UTC
