### ISSUE TITLE
Firmware upgrade progress not displayed in GUI

### ISSUE THREAD

**Issue by glitter-ball** [proddy/EMS-ESP#513] opened 2020-09-23 12:07 UTC
**Bug description**
When a new .bin firmware file is dragged and dropped into the v2 GUI, the update does not proceed as code authors think it should.

**Steps to reproduce**
Drag and drop new .bin file into the upgrade page.

**Expected behaviour**
When you drag&drop the firmware it will start the upload (to 100%) and then show the green box with the message 'activating new firmware...'. Then it will de-compile the firmware and reboot which can easily take up to a minute.

**Actual behaviour** 
Upload bar quickly moves to 100% then no further feedback from GUI. Navigating off page produces orange “Upload cancelled by user”. Reloading GUI shows updated firmware ID so upload has worked but no progress pop ups seen.

**Comment by glitter-ball** [comment] 2020-09-23 12:13
Anyone else seeing this behaviour too? Did try and video it but can’t upload MP4s and hosting it somewhere else was messy.

**Comment by proddy** [comment] 2020-09-23 12:27
Which browser are you using?

**Comment by glitter-ball** [comment] 2020-09-23 12:48
I get the same behaviour in latest versions of Firefox and Edge, both on Windows 10.

**Comment by MichaelDvP** [comment] 2020-09-23 13:06
I have also firefox (tweaked) and edge (stock) on win10. With both i see the expected behaviour. Here for Edge:
After drop the bin:
![uploading](https://user-images.githubusercontent.com/59284019/94015371-10b9c100-fdad-11ea-8561-48a37f481d64.png)
a few secondes later:
![upload_ok](https://user-images.githubusercontent.com/59284019/94015389-13b4b180-fdad-11ea-81f7-33e2544a401f.png)
The box also works if the window is small. 
![upload_ok_small](https://user-images.githubusercontent.com/59284019/94015846-ae14f500-fdad-11ea-9d97-9ffe96afdb61.png)
The green box disapears after one or two seconds, it takes some more time until  esp is up again.

@glitter-ball do you see the green box when save settings, after login, or never?

**Comment by glitter-ball** [comment] 2020-09-24 10:17
I've never seen the "Activating new firmware" popup above.

I get the green popup for login and settings saving in Firefox. There's also something else odd going on. When I attempt to connect in Microsoft Edge, I get:
![image](https://user-images.githubusercontent.com/57917148/94132362-1835a480-fe57-11ea-856a-ee416e0b7dfa.png)
and the login page never appears, so I can't check the popups in Edge. Edge on my iPhone does work OK with popups. Connecting with Firefox does bring up the login page but I wait 10-15 seconds with a blank white screen for it to appear.

**Comment by glitter-ball** [comment] 2020-09-24 17:43
Tried shrinking the Firefox window to make sure nothing getting lost behind Windows task bar. No good.

But observed something new. Watched MQTT Explorer. There is a gap in the data stream (in red here) after the FW uploads, but, crucially there is no 'info' telegram and the uptime in the heartbeat telegram hasn't reset:
![image](https://user-images.githubusercontent.com/57917148/94180075-5c479a00-fe95-11ea-8557-c856bca7ab5a.png)

When I then try and kick the GUI back into life, there's another hiccup and eventually it recovers and the missing info telegram and update up time in heartbeat:
![image](https://user-images.githubusercontent.com/57917148/94180211-90bb5600-fe95-11ea-9fee-881eed23730f.png)

So, although the firmware uploads and there is a pause in MQTT traffic, I'm not sure the device actually restarts until I poke it somehow, whereupon it resets the uptime counter and sends the info telegram.

Hopefully, there's a clue in all this!

**Comment by proddy** [comment] 2020-09-30 13:08
I still can't reproduce this error (GUI upload on Win10). Anyone else seeing the same behaviour?

**Comment by glitter-ball** [comment] 2020-09-30 16:06
Maybe I should wipe the device <gulp> and see if it still happens? Very odd...

**Comment by proddy** [comment] 2020-09-30 18:30
lets just wait a while to see if anyone else has the issue. There are so many factors involved (firewalls, browser plugins, wifi strength). The web upload basically uses the same logic as the espota.py so if that is working I would expect the web upload to work too.

**Comment by glitter-ball** [comment] 2020-09-30 19:00
OK. One option would be to wireshark the session and see what traffic’s actually passing between browser and device. That would narrow things down a bit.

**Comment by proddy** [comment] 2020-10-07 19:39
closing this to prepare for 2.1. Will re-open if others have the same issue.

**Closed by proddy** 2020-10-07 19:39 UTC
Labels: bug
