### ISSUE TITLE
Protocol / Queue handling issue

### ISSUE THREAD

**Issue by susisstrolch** [proddy/EMS-ESP#151] opened 2019-07-16 18:06 UTC
Today my Logic Analyzer arrived, so I found the time to look what's going on on EMS-Bus.
Environment:
- RC35 (DeviceID:0x10 ProductID:86 Version:01.11)
- MC10 (DeviceID:0x08 ProductID:72 Version:02.07)
- EMS-ESP version 1.8.1b17
- - external power supply
- - tx_mode = 0

Issue 1 - EMS-ESP continues sending, even not being polled again
```
1. MC10:	08 0B 16 00 FF 5A 64 00 06 FA 0A 01 0F 64 64 02 
	        08 F8 0F 0F 0F 0F 1E 05 04 09 09 00 6D 00
2. ESP:	0B 00
3. MC10:	   0B 00 89 00 85
4. ESP:		  0B 88 14 00 20 E4 00
<200ms pause>
```
1. MC10 sends a **MC10Parameter** message to us.
2. We acknowledge with "0B <BRK>" -> ok, fini
3. MC10 echos our acknowledge???
    The <BRK> from MC10 looks fine, it's approx. 1.035ms
4. We continue to poll MC10, which is simply ignored by the busmaster by not sending an echo.
![Selection_023](https://user-images.githubusercontent.com/1432955/61317621-a8b03800-a803-11e9-8e7f-4f353fc4856e.jpg)

Issue 2 - pretty similiar to Issue 1
```
1. RC35:	10 0B 3E 00 00 00 00 7D 00 00 00 00 00 00 00 00
	        00 11 05 00 E9 00
2. ESP:	0B 00
3. RC35:	   0B 00
4. ESP:		  0B 90 3D 00 20 80 00
5. RC35:		     0B 90 7A
<200ms pause>
```
1. RC35 sends a **HK1MonitorMessage** to us
2. We respond with "0B <BRK>" -> ok, fini
3. RC35 echos our acknowledge
4. We start sending w/o request
5. Busmaster stops echo after 2nd byte and stays silent for 200ms.
![Selection_020](https://user-images.githubusercontent.com/1432955/61318135-ab5f5d00-a804-11e9-82a4-5b92fd36bf9a.jpg)

**Comment by proddy** [comment] 2019-07-16 18:51
interesting, if you use tx_mode=2 (your implementation) does it start to clear up a little?

**Comment by susisstrolch** [comment] 2019-07-16 19:19
That will be the next step.. first, I have to create triggers for the LA - especially on Rx / Tx BRK.
digitalWrite doesn't work in emsuart - that leads to reboot loops from watchdog.

**Comment by proddy** [comment] 2019-07-17 07:20
getting digitalWrite to work in an ISR is tricky. although it is atomic its slow. I've managed to do this before in earlier versions using the LED to show BRKs using

`WRITE_PERI_REG(PERIPHS_GPIO_BASEADDR + (state ? 4 : 8), (1 << EMSESP_Status.led_gpio)); // 4 is on, 8 is off`

**Comment by susisstrolch** [comment] 2019-07-17 11:00
Jep.. it was more a "which one to use and how/where to mark the actions".
Anyway...
Added two markers to visualize whats going on. One is related to Rx, the other to Tx.
Short Tx mark is set when we fill the Tx FIFO. Long Tx mark is set when we generate a BRK, **after** waiting for Tx-FIFO empty.
Rx mark (long) is set as soon as we detect a BRK on Rx.

Now, Iet's have a look at the protocol problem (still in tx_mode 0):

1. MC10 sends a MC10Parameter message to us.
![Selection_025](https://user-images.githubusercontent.com/1432955/61367830-bf4ea180-a88c-11e9-9dde-d47597ec31d0.jpg)

![Selection_026](https://user-images.githubusercontent.com/1432955/61367910-eefda980-a88c-11e9-84a8-158633595434.jpg)

2. At the blue marker you see that ESP acknowledges with a ```0B <BRK>``` - which is imho wrong, because the command isn't a poll request. So we should answer with ACK or NACK.
3. EMS acknowledges with ```0B <BRK>``` - so far ok - and, because the ```<BRK``` terminates a communication - EMS assumes that the bus is free.
![Selection_027](https://user-images.githubusercontent.com/1432955/61370216-2cb10100-a892-11e9-8368-1f39c6dad2de.jpg)
4. ESP however continues to send - which is politely ignored by EMS.
![Selection_028](https://user-images.githubusercontent.com/1432955/61370233-36d2ff80-a892-11e9-921b-6d38845dbd12.jpg)

So, I suggest the following extensions to protocol handler:
If we are targeted by the message AND if bit7 isn't set we have a direct telegram, which should be ACKed with the 04 (?? - have to lookup the docs) - and after that by sending a ```0B <BRK```.
In addition, ESP should wait for the next poll request before sending the next telegram.

The ```tx_mode 2``` is my next target...

**Comment by susisstrolch** [comment] 2019-07-17 11:01
Uups - seems my JPEG rendering is a bit too conservative...

**Comment by susisstrolch** [comment] 2019-07-18 21:10
Ok, here's the next one...
Switching to alternate Tx/Rx is much too late after reboot. The EMS-Bus keeps pulled low to long.
Green Marker: echo from reboot
Blue Marker: Tx moved over to alternate Tx
As you can see the EMS is pulled down for >4s after reboot...
![Selection_030](https://user-images.githubusercontent.com/1432955/61492211-29606700-a9b1-11e9-854b-0141bd314f02.jpg)

Zoomed in before blue marker:
![Selection_031](https://user-images.githubusercontent.com/1432955/61492255-41d08180-a9b1-11e9-864b-da322387b8e0.jpg)

**Comment by proddy** [comment] 2019-07-18 21:22
the uart being initialized and the interrupts enabled at the last minute was by design as to not interfere with anything else that was happening during bootup (serial transmissions, wifi, mqtt, websockets etc). It seemed the sensible thing to do at the time as I didn't want to fill up the Rx buffers. The logic is in line 1569 of ems-esp.cpp. It should be safe to move it forward as you suggested although I'm not sure what advantage it will have?

**Comment by proddy** [comment] 2019-07-18 21:28
btw how you finding the dslogic? I have one too from https://www.dreamsourcelab.com/product/dslogic-plus but found it quite cumbersome to use. I often switch over to a 4 EUR USB logic analyzer and using Saleae's free [software](https://support.saleae.com/logic-software/latest-beta-release)

**Comment by susisstrolch** [comment] 2019-07-18 21:36
Advantage is not to block the EMS bus - there's nothing on the line during this time...

**Comment by proddy** [comment] 2019-07-18 21:40
I see. I would have expected it wouldn't pull down the line as the D7/D8 pins are not activated though ?

**Comment by susisstrolch** [comment] 2019-07-18 21:48
Next one... found in tx_mode 2...
Between receiving a "ITS_TO_ME" telegram and processing we could be interrupted / delayed by WIFI/MQTT transmission.
Currently, the tx doesn't care about the Rx status. This will lead to overlapping / misleading operations on the EMS bus.
Green marker: EMS is sending a poll request
Dark green marker: Poll request is processed
Overview:
EMS sends a poll request which is handled ~130ms after the request. Meanwhile, the next device is sending, which gets disturbed by us.

![Screenshot from 2019-07-18 23-28-05](https://user-images.githubusercontent.com/1432955/61494204-d6d57980-a9b5-11e9-9c09-badf39e94f0e.png)
Request details:
![Screenshot from 2019-07-18 23-29-42](https://user-images.githubusercontent.com/1432955/61494333-30d63f00-a9b6-11e9-9985-684821bfe6f4.png)

Response disturbing bus:
![Screenshot from 2019-07-18 23-31-41](https://user-images.githubusercontent.com/1432955/61494379-52cfc180-a9b6-11e9-84b3-a2582025504f.png)

IMHO, Tx should honour the Rx-Status - simply fail if Rx != IDLE...

**Comment by susisstrolch** [comment] 2019-07-18 21:51
> btw how you finding the dslogic
It's a really great tool - needs a bit time to find out how to work, but after that you find anything you like!!

**Comment by proddy** [comment] 2019-07-18 22:01
jealous !

**Comment by susisstrolch** [comment] 2019-07-18 22:02
> I see. I would have expected it wouldn't pull down the line as the D7/D8 pins are not activated though ?

I also don't understand why they are pulled down. My first thought was that it happens in the Arduino core - at least the traces looks alike...

**Comment by susisstrolch** [comment] 2019-07-18 22:06
> jealous !

Playground :) accepted by Susi :))
(won't talk about the 3D printer in background)

**Comment by susisstrolch** [comment] 2019-07-18 22:23
Somehow we must handle the duedate of the received package. 
Maybe by a timestamp, If delta > 100ms we won't process the Tx anymore...

**Comment by proddy** [comment] 2019-07-18 22:34
> > jealous !
> 
> Playground :) accepted by Susi :))
> (won't talk about the 3D printer in background )
> 
> ![IMG_5961](https://user-images.githubusercontent.com/1432955/61495625-c58e6c00-a9b9-11e9-9852-649b41e8abb4.JPG)

3D printer's on my wish list too. Velleman make some nice kits.

**Comment by susisstrolch** [comment] 2019-07-18 22:40
Yep... but it needs some tweeks until it's really usable...
F.e. the sliders are suboptimal...
Simply ping me if you go to K8800...

**Comment by susisstrolch** [comment] 2019-07-18 22:43
Totaly off-topic:
iPhone8p holder for the bycicle.. printed in PLA+Carbon...
![IMG_5962](https://user-images.githubusercontent.com/1432955/61496942-2750d500-a9be-11e9-919b-d39c918ed0a0.JPG)

**Comment by bbqkees** [comment] 2019-07-25 08:31
> 
> 
> > I see. I would have expected it wouldn't pull down the line as the D7/D8 pins are not activated though ?
> 
> I also don't understand why they are pulled down. My first thought was that it happens in the Arduino core - at least the traces looks alike...

Is the EMS bus itself actually blocked?
If I recall correctly when the TX input is floating or 0 the TX transistor is active (so the current is drawn through the resistors).
Could be the I/O of the ESP is pulled low at boot so the analyzer sees a logic 0 at those pins but the EMS bus itself might be just fine.

**Comment by susisstrolch** [comment] 2019-07-25 08:43
It‘s simply because GPIO15 has a pulldown resistor connected. Otherwise (GPIO15 open) the ESP tries to boot from SD-Card...

Sent by mobile device

**Comment by proddy** [comment] 2019-07-25 08:44
GPIO15 (D8) which we use for Tx is automatically pulled high by the ESP8266 during boot up, which causes the block on the EMS bus. In the code its forced down so there's only a very short window now (3 bytes I think).

**Comment by susisstrolch** [comment] 2019-07-25 09:42
> GPIO15 (D8) which we use for Tx is automatically pulled high by the ESP8266 during boot up
No... GPIO15 has a pull down (10k) on (nearly) all boards (Wemos, NodeMCU).

The adapter board itself is inverting the Tx signal - pulling current from EMS-Bus when Tx (GPIO15) is low.
So, during boot the EMS-Bus was pulled low for (my impression) much to long.

**Comment by bbqkees** [comment] 2019-07-25 10:03
Yes indeed.
But you only block slave TX for a short moment, the EMS master can still send uninterrupted.

**Comment by susisstrolch** [comment] 2019-07-26 12:13
@proddy we have a protocol handling issue when sending to EMS bus. It happens with tx_mode 0 and also with tx_mode 2.
Look at those traces:
```
(00:09:16.948) ems_parseTelegram: 00 01: 8B
(00:09:16.948) emsuart_tx_buffer: 00 01: 0B 90 3E 00 20 8C
(00:09:16.964) ems_parseTelegram: 00 02: 0B 90 3E 00 20 8C
(00:09:16.964) 0B 90 3E 00 20 8C
(00:09:16.964) echo:telegram: 0B 90 3E 00 20 (CRC=8C) #data=1
(00:09:17.078) ems_parseTelegram: 00 02: 10 0B 3E 00 00 00 00 7D 00 00 00 00 00 00 00 00 00 00 05 00 AD
(00:09:17.078) 10 0B 3E 00 00 00 00 7D 00 00 00 00 00 00 00 00 00 00 05 00 AD
(00:09:17.080) emsuart_tx_buffer: 00 01: 0B
(00:09:17.085) ems_parseTelegram: 00 01: 0B
(00:09:17.085) emsuart_tx_buffer: 00 01: 0B 90 3D 00 20 80
[557087] ** error sending buffer: BRK
(00:09:17.297) ems_parseTelegram: 00 01: 89 00 86 90 
```
`(00:09:16.948) ems_parseTelegram: 00 01: 8B`                             Bus master sends poll request
`(00:09:16.948) emsuart_tx_buffer: 00 01: 0B 90 3E 00 20 8C`       We send a query for 0x10
`(00:09:16.964) ems_parseTelegram: 00 02: 0B 90 3E 00 20 8C`   We get the echo
`(00:09:17.078) ems_parseTelegram: 00 02: 10 0B ....`                   We process the data
`(00:09:17.080) emsuart_tx_buffer: 00 01: 0B`                                 We tell Busmaster we're ready
`(00:09:17.085) ems_parseTelegram: 00 01: 0B`                             Busmaster echo
`(00:09:17.085) emsuart_tx_buffer: 00 01: 0B 90 3D 00 20 80`       We send again, w/o invitation/poll
`[557087] ** error sending buffer: BRK`                                            Bus master signals "shut up"

The issue is that we interpret the echo as a poll request because of masking out the "poll bit" from Target ID.

**Comment by proddy** [comment] 2019-07-26 13:21
funny, I noticed that too this morning when I was trying to debug why the 0x19 MonitorSlow messages were getting blocked (buffer of 32 was too small). I saw many telegrams with a length of 1 and a value of 0x19 which was a recursive echo->poll

**Comment by susisstrolch** [comment] 2019-07-26 16:15
Seems I have a more stable version at the moment. Much less Rx-idle warnings and no Tx Brk or Tx Timeout during the last hour. 
Still have to clean up a bit and 
- add log debug with more Info (Junkers)
- show reboot reason when connecting 


Sent by mobile device

**Comment by proddy** [comment] 2019-07-26 16:25
great, thanks Juergen. Amazing how you can code in these extreme heats. Shall I take a look at fixing the echo/poll issue or have you already squished that bug?

**Comment by susisstrolch** [comment] 2019-07-26 17:04
I‘ve already fixed that one. 
Must be crosschecked by Junkers owner. 


Sent by mobile device

**Comment by susisstrolch** [comment] 2019-07-26 17:06
02:01:02.556) echo:telegram: 0B 90 3E 00 20 (CRC=8C) #data=1
(02:01:03.290) echo:telegram: 0B 90 3D 00 20 (CRC=80) #data=1
(02:01:03.730) echo:telegram: 0B 90 06 00 20 (CRC=6C) #data=1
(02:01:04.049) echo:telegram: 0B 88 18 00 20 (CRC=D4) #data=1
(02:01:12.102) echo:telegram: 0B 88 19 00 20 (CRC=D0) #data=1
(02:01:12.626) echo:telegram: 0B 88 33 00 20 (CRC=78) #data=1
(02:01:12.886) echo:telegram: 0B 88 16 00 20 (CRC=EC) #data=1
(02:01:13.176) echo:telegram: 0B 88 14 00 20 (CRC=E4) #data=1


Sent by mobile device

**Comment by proddy** [comment] 2019-07-27 06:14
I remember from https://github.com/proddy/EMS-ESP/issues/103#issuecomment-487408779 the Junkers/HT3 sent out Polls without the MSB and that seemed to also work on Buderus so I changed it for everyone. What's peculiar for Junkers is if the Poll has no MSB set how does it distinguish from an acknowledgement as they are now identical?

When you're happy with the changes do a PR and I'll ask a few of the Junkers boys to give it a test.

**Comment by susisstrolch** [comment] 2019-07-27 06:39
After reading through #103 it‘s more that Junkers always (read, write, poll, ack) has an inverted ID bit.

**Comment by proddy** [comment] 2019-07-27 07:14
Yes, on startup it pings for known Junkers models and if one is detected `EMS_Sys_Status.emsReverse` is set which is used through out the code to unset the MSB.

**Comment by susisstrolch** [comment] 2019-07-28 09:23
I‘m thinking of changing the Junkers detection to a more protokol related approach. 
- On Start, go to listen only mode until the first full telegram is received. 
- if SourceID > 0x80 we have a inverting protokoll (Junkers, ???) otherwise the Buderus EMS. 

This flag will consistently used for Poll, Write, Read and Ack. 
In Addition I want to send this info, including the txmode, as a MQTT info.

**Comment by proddy** [comment] 2019-07-28 10:41
That's a good approach. Do you want some help implementing this?

**Comment by susisstrolch** [comment] 2019-07-28 11:57
No, got playtime permission 😁
Will cleanup my changes and start implement it later. 

BTW: uptime 1d 3h 38m in txmode 2…

Von meinem iPad gesendet

**Comment by proddy** [comment] 2019-07-28 13:39
Ok. I'd like wrap up 1.8.1 and push it to Master so we can work on the next major 1.9 version with a more optimized web interface. Any objections on finalizing the dev branch today/tomorrow ?

**Comment by susisstrolch** [comment] 2019-07-28 14:25
No, should work out so far...

**Comment by susisstrolch** [comment] 2019-07-28 16:38
Just pushed a intermediate version, with most of my changes (also Junkers) in.
Please have a look...

**Comment by susisstrolch** [comment] 2019-07-28 17:45
... also a forgotten initialization and logmode j - like jabber. 
Tomorrow I‘ll rebase the branch so it‘s easier for you to merge to dev and Master.

**Comment by proddy** [comment] 2019-07-28 18:09
ok. You have access to the EMS-ESP github so feel free to push any changes direct to dev

**Comment by proddy** [comment] 2019-07-28 18:20
Actually, shall I release 1.8.1 as it is to master now and merge your new changes to the next dev version (1.9) ?

**Comment by susisstrolch** [comment] 2019-07-28 18:58
Yes, makes sense 

Sent by mobile device

**Comment by proddy** [comment] 2019-07-29 12:53
ok, dev branch is now v1.9 and the next playground to experiment with. You can merge your txmode2 branch anytime you want.

**Comment by susisstrolch** [comment] 2019-07-29 13:38
I think keeping it separate for a whole will ease debuggung for Junkers devices. 

Sent by mobile device

**Comment by susisstrolch** [comment] 2019-07-29 17:19
@proddy TxMode2 and Junkers autodetect should work so far.
So we need a volunteer compiling and testing the txmode2 branch. 
In this branch you will also find a Description for HT3 and a lot EMS2 types. 

Ah, for easier debug I‘ve added ‚log j‘, which also shows raw Tx/RX buffers (Junkers debug).

**Comment by proddy** [comment] 2019-07-29 18:09
wonderful! I'll test tonight and reach out the the HT3 guys to see if they can test

**Comment by proddy** [comment] 2019-07-30 07:47
Been running the txmode2 branch for 12hrs now with no crashes and hardly any corrupt telegrams. Looking good!

**Comment by susisstrolch** [comment] 2019-07-30 08:27
Great!
Now we need the result of the Junkers users. 
About the reboots - I suspect MQTT or telnet. 
Maybe we should ad a watchdog feed    before calling them. 

Sent by mobile device

**Comment by proddy** [comment] 2019-07-30 08:58
with 1.8.1 I would get reboots every 10-15 mins with tx_mode 2, but none with tx_mode 0 so I don't expect its telnet/mqtt related. you can switch all that off (set mqtt_ip and set publish_time 0) and it still happens. Anyway seems better in 1.9

**Comment by susisstrolch** [comment] 2019-07-30 14:52
We should really try the watchdog feed before each timeconsuming function call. 
Because it‘s the software watchdog which gets triggered we don‘t get a stacktrace. 
So we must iterate by try and error.

**Comment by proddy** [comment] 2019-07-30 15:05
yes, we need to keep the code in ISRs non-blocking and highly optimized. `emsuart_tx_buffer()` has grown in complexity quite significantly since 1.7 with many loops and race conditions.

**Comment by proddy** [comment] 2019-07-30 15:18
Or disabled wdt before the Tx is called from ems.cpp with `ESP.wdtDisable()`and enable it after the acknowledgement poll has been received with `ESP.wdtEnable(0)`

**Comment by susisstrolch** [comment] 2019-07-30 15:45
I‘ll upload a log in jabber mode - there you can see that Tx/Rx aren‘t the bottlenecks.

**Comment by susisstrolch** [comment] 2019-07-30 16:57
And here an interesting arcticle about soft-wtd:

https://www.sigmdel.ca/michel/program/esp8266/arduino/watchdogs_en.html#ESP8266_WDT_TIMEOUT

**Comment by susisstrolch** [comment] 2019-07-31 09:23
pushed a new release of txmode2 branch which injects wdtfeed() in MyESP.loop.

**Comment by proddy** [comment] 2019-07-31 11:23
In all versions up to 1.8.0  I had this line in MyESP.loop():

`yield(); // ...and breath`

which somehow got lost after 1.8.1. I think it does the same as the `wdtfeed()` no?

**Comment by susisstrolch** [comment] 2019-07-31 18:29
It‘s still in. But yield does more than calming the WTD - it also cares about WIFI stuff. 
wtdFeed only restarts/resets the HW and SW watchdog and doesn’t have any further overhead. 

Sent by mobile device

**Comment by bbqkees** [comment] 2019-08-01 07:18
So I've been running the latest build from yesterday evening in the txmode2 branch.
At first I got lots of reboots (every 2 minutes or so) but now its been running for 10h without hickups (jack powered, not bus powered).

**Comment by proddy** [comment] 2019-08-01 07:38
> It‘s still in. But yield does more than calming the WTD - it also cares about WIFI stuff. wtdFeed only restarts/resets the HW and SW watchdog and doesn’t have any further overhead. Sent by mobile device
> […](#)
> Am 31.07.2019 um 13:23 schrieb Paul ***@***.***>: In all versions up to 1.8.0 I had this line in MyESP.loop(): yield(); // ...and breath which somehow got lost after 1.8.1. I think it does the same as the wdtfeed() no? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

There is also a delay(1) in the ems-esp.cpp loop I used to calm down the wifi after seeing how ESPhome and other projects did this because of ardunio 2.5.0. It might no longer be necessary?

**Comment by susisstrolch** [comment] 2019-08-01 09:09
delay() is also doing the WIFI and SWDT handling, so it shouldn't hurt at all.
But I can try to remove it...

**Comment by susisstrolch** [comment] 2019-08-02 06:00
Found that one: https://github.com/letscontrolit/ESPEasy/issues/2477

**Comment by proddy** [comment] 2019-08-02 06:08
> Found that one: [letscontrolit/ESPEasy#2477](https://github.com/letscontrolit/ESPEasy/issues/2477)

nice, didn't know you could do that. Let's add that too as it'll help us find the root cause for the WDT resets.

**Comment by bbqkees** [comment] 2019-08-02 10:14
Possibly unrelated but ran txmode2 firmware for 20+ hours (with an open but idle Telnet session) without problems.
However, after doing 'log v' it rebooted after a few minutes.

**Comment by proddy** [comment] 2019-08-02 14:00
thats good news for @susisstrolch new tx code. the logv does a lot of string manipulation (as I avoid using the String library and sprintf() ) so most probably its a memory error I need to look into.

**Comment by proddy** [comment] 2019-08-02 18:53
@bbqkees  @susisstrolch  also unrelated - I uploaded my latest web version under the newweb branch if you want to play with it. Still need to refine a few things but I think its stable. Look carefully at the CHANGELOG on how to build it because the build scripts have also changed. I'm off now and will pick things up when I'm back in a week.

**Comment by bbqkees** [comment] 2019-08-05 07:44
Ok will try.
The txmode2 build from last week is still running here uninterrupted at 3 days (bus powered).
Telnet session still active.

**Comment by susisstrolch** [comment] 2019-08-05 08:28
I have 2days 6hr parasitare Mode. 

Sent by mobile device

**Comment by bbqkees** [comment] 2019-08-08 12:27
@proddy Took me some time because of lots of build errors but I was able to build the firmware in the end.

The newweb branch needs two additional libraries: ESPAsyncUDP and ESPAsyncWebServer. (PIO Home->Find libraries->type name-> install)
Maybe its Windows or just my particular setup but the gulp build did not work with the 'debug' parameter.
So did `node gulp` command in the correct folder and after that went through fine and the compacted web code files were added to the 'webh' folder, the build in pio went Ok. 

The new web interface looks great, will test it over the weekend.

**Comment by proddy** [comment] 2019-08-08 12:53
Did you use the latest platformio.ini example file? I would have expected
pio to download the libraries automatically.

**Comment by bbqkees** [comment] 2019-08-08 12:58
Yes, the new one with the 'pre:scripts/buildweb.py' etc.

I had the same issue when you added f.i. OneWire initially.

**Comment by proddy** [comment] 2019-08-08 13:08
That's strange. In theory if you remove the whole .pio folder/directory it should go fetch all the libs. I'll try on a fresh win install this weekend

**Comment by proddy** [comment] 2019-08-11 14:56
@bbqkees tested on a fresh win install with platformio 4 and you shouldn't need to download anything manually. As soon as the platformio.ini file is there it will automatically fetch the latest libraries. We can look at your config next week.

@susisstrolch I merged the txmode2 branch into the newweb branch and it's been running fine for the last 8hrs. Eventually I'll move all this into dev which is 1.9.0 so let me know if you're planning any further changes. We still need to test with Junkers.

**Comment by proddy** [comment] 2019-08-27 10:24
closing for now. txmode2 merged into dev.

**Closed by proddy** 2019-08-27 10:24 UTC
Labels: bug
