### ISSUE TITLE
v2.1.1b7 - release for ESP32 doesn`t work

### ISSUE THREAD

**Issue by sq4bja** [proddy/EMS-ESP#669] opened 2020-12-18 11:52 UTC
Hi,
The new firmware from dev tree 2.1.1b7 doesn't work (compiled for esp32). Now, i'm using 2.1.1b6. I'm trying to upload BIN file form github using web interface and i'm getting "Error during upload"
![obraz](https://user-images.githubusercontent.com/26671657/102611707-c3d95280-412f-11eb-932f-d74793c3b022.png)

**Comment by MichaelDvP** [comment] 2020-12-18 13:53
I can not confirm, i've downloaded the bin and flashed via upload, no issues.
Please try download again.

**Comment by sq4bja** [comment] 2020-12-18 13:58
The same again. Firmware file looks OK.
![obraz](https://user-images.githubusercontent.com/26671657/102622501-6817c500-4141-11eb-9979-3c55828840df.png)

**Comment by MichaelDvP** [comment] 2020-12-18 14:38
Try reloading the webpage before uploading, and/or restart esp. My working downloaded file is exactly same size.

**Comment by sq4bja** [comment] 2020-12-18 14:43
I just done it. It doesn`t help. Still the same error.

**Comment by MichaelDvP** [comment] 2020-12-18 15:15
Does flashing main or b6 work?

**Comment by sq4bja** [comment] 2020-12-18 15:28
I can`t flash again b6 or any other. It looks like errot in b6-ci firmware. 
Only the use of espota.py helped. Now I have B7. It looks like some previous firmware bug that made it impossible to upgrade via www.
Tom

**Comment by SpaceTeddy** [comment] 2020-12-20 12:13
@sq4bja I had similar issues with downloading an compiling the dev tree. Compiling was OK, but after update OTA or web, I was still on 2.1.0. @MichaelDvP gave me the hint to download the the bin file. after downloading this bin file via web it worked fine.

**Comment by proddy** [comment] 2020-12-22 08:45
duplicate of #653

**Closed by proddy** 2020-12-22 08:45 UTC
Labels: bug
