### ISSUE TITLE
Boiler temperature is undefined (from > 1.9.5 B42)

### ISSUE THREAD

**Issue by sq4bja** [proddy/EMS-ESP#345] opened 2020-03-08 18:25 UTC
After upgrade from b42 to higher i lost boiler temperature. GB072 + R310.
On WWW panel boiler temperature is undefined ℃
On telnet connection it looks like this:

Boiler temperature: ? C
Warm water storage temperature1: ? C
Warm water storage temperature2: 37.6 C

Previously Boiler temperature was the same like WW storage temperature 2.

Tom

**Comment by sq4bja** [comment] 2020-03-08 18:38
![obraz](https://user-images.githubusercontent.com/26671657/76168951-4fbb5880-6174-11ea-8909-c3d8f1f52e1e.png)

**Comment by proddy** [comment] 2020-03-08 18:39
yes, there's been a lot of back-and-forth on this topic. In previous versions, the boiler temperature was incorrectly specified to keep backward compatibility with Junkers I had to make some changes. It's apparently the temperature of the internal boiler, like on a combi.

I don't think you have a boiler, unless it's external, right?

**Comment by sq4bja** [comment] 2020-03-08 18:44
Yes, i have combi boiler GB072 with external storage tank. Boiler Temperature previously show a temperature od water i storage tank.

**Comment by proddy** [comment] 2020-03-08 19:11
does your RC310 show any boiler temperatures? If so, which ones and what does it call them?

**Comment by sq4bja** [comment] 2020-03-08 19:42
Yes. Look at the picture below. 
![obraz](https://user-images.githubusercontent.com/26671657/76169917-5b5f4d00-617d-11ea-91ad-09edf471b427.png)

**Comment by proddy** [comment] 2020-03-08 19:47
great and kind you find these back in the `info` command so we can do a mapping?

**Comment by sq4bja** [comment] 2020-03-08 19:51
Ok, i can see it here:
Warm water storage temperature2: 27.3 C
and here:
Warm Water current temperature: 27.3 C

**Comment by proddy** [comment] 2020-03-08 20:50
ok, in 1.9.5b53 I made a few changes and show in the web the DHW temp (which is the same as the warm water current temperature). Also renamed the storage temperature2 and temperature1 to something more meaningful, using 'intern' and 'extern'. hope it makes sense?

**Comment by sq4bja** [comment] 2020-03-08 21:30
Looks OK now. Thanks.
![obraz](https://user-images.githubusercontent.com/26671657/76171493-61a8f580-618c-11ea-86ee-cde8488c46dd.png)

**Comment by proddy** [comment] 2020-03-08 21:31
I also changed the web interface so you would need to rebuild that too. platformio should have it done it for you, unless you change the scripts.

**Comment by sq4bja** [comment] 2020-03-08 21:33
I`m getting new firmware from Update link on web interface. Is it good?

**Comment by proddy** [comment] 2020-03-08 21:52
Hmmm. I’ll double check.

**Comment by proddy** [comment] 2020-03-09 10:33
think it was just cached in your browser, I couldn't reproduce. Closing this issue now.

**Closed by proddy** 2020-03-09 10:33 UTC
Labels: bug
