### ISSUE TITLE
Difficulty changing thermostat mode in home assistant

### ISSUE THREAD

**Issue by mrfixit1** [proddy/EMS-ESP#208] opened 2019-10-11 08:20 UTC
I'm finding it difficult to switch thermostat modes in HA with my RC20.

For example, switching from Auto to Off changes the set temperature as expected, but:
- the HA UI shows 7 Auto;
- the HA log says:  ERROR (MainThread) [homeassistant.components.mqtt.climate] Invalid modes mode: low
- the ems-esp says: 
Thermostat stats:
  Thermostat: RC20/Moduline 300 (ProductID:77 Version:03.03)
  Thermostat time is 10:18:30 11/10/2019
  Heating Circuit 1
   Current room temperature: 18.2 C
   Setpoint room temperature: 7.0 C
   Mode is set to low

I'm using the current climate.yaml with the modes "auto", "heat" and "off".

Any ideas?

**Comment by proddy** [comment] 2019-10-11 08:37
yes, I see the issue. I'll fix it.

**Comment by proddy** [comment] 2019-10-12 11:15
fixed in 1.9.2b6 if you would be so kind to verify

**Comment by mrfixit1** [comment] 2019-10-12 18:46
Fix verified OK: switching thermostat modes now works well, the mode name and symbols under the thermostat dial in the UI are correct and the dial colour changes between green for auto and orange for heat (i.e. manual). The lights on my RC20 change immediately, although the web UI on my Android phone needs a few seconds to catch up - I guess this is inherent. Thanks for the speedy updates. 

I needed to apply the following minor tweaks to get everything working:
1. npm install instead of npm ci to install the gulp module, as the latter gave an error;
2. as mentioned in #187, to resolve compile errors I added lib_ignore = Time to platformio.ini; 
3. climate_thermostat instead of climate.thermostat_hc1 in ui-lovelace.yaml, as the latter gave a 'not recognised' error.

**Comment by proddy** [comment] 2019-10-13 12:52
thanks @mrfixit1 for pointing this out. I fixed #1 with checking in the package-lock file. Also #3 was a typo. Still confused with #2 and trying to reproduce.

**Comment by proddy** [comment] 2019-10-13 12:59
can't reproduce #2. Tried with a fresh install (on Ubuntu then)
```
git clone --branch=dev https://github.com/proddy/EMS-ESP.git
cd EMS-ESP/tools/webfilesbuilder/
npm ci
cd ../..
pio run
```

works all the time. Try removing your whole .pio folder.

**Comment by mrfixit1** [comment] 2019-10-13 19:37
Re. 1, npm ci now works for me as well, thanks for the fix.

Re. 2, leaving the lib_ignore = Time out now gives a series of compile errors starting with src\TimeLib.h:20:16: error: redeclaration of 'timeNotSet'. The corresponding error message in TimeLib.h is:
enum timeStatus_t::timeNotSet = 0
redeclaration of 'timeNotSet'

I've also some more collateral damage: the history graph from sensor.current_room_temperature has disappeared and the Last shower duration shows as Unknown.

**Comment by proddy** [comment] 2019-10-13 20:12
I forgot about those sensors. Didn't think anyone used them anymore since there is HA climate component. I'll update the sensors.yaml file.

**Comment by mrfixit1** [comment] 2019-10-14 18:16
The temperature history graph is back, thanks for the fix.

**Comment by proddy** [comment] 2019-10-14 18:56
can we close this issue?

**Comment by mrfixit1** [comment] 2019-10-14 18:58
Do you have any suggestions where to look to get the shower timer working again?

**Comment by proddy** [comment] 2019-10-14 19:30
lol. I thought I was the only one using the shower timer! Ironically this was why I started the project in the first time, to stop my daughter from taking really long showers!

Anyway I committed some changes today to the HA configuration (sensors and automation) and it should work again. Let me know if it doesn't.

**Comment by mrfixit1** [comment] 2019-10-15 12:46
The shower timer is useful for my environmental awareness too ;-). 

I updated the ems-esp code to v1.9.2b9 and copied the new changes to the automations and sensors yamls, but the shower duration and last shower at times still aren't showing.

Any further tips are welcome.

**Comment by proddy** [comment] 2019-10-15 13:06
Oops. Saw I forgot to update the sensors.yaml file.  I think this bit

```
- platform: mqtt
  state_topic: 'home/ems-esp/showertime'
  name: 'Last shower duration'
  force_update: true
```

should have this line added:

```
 value_template: '{{ value_json.duration }}'
```


I don't have access to HA to check but try that and stimulate using something like MQTT Explorer and publish:

topic: home/ems-esp/shower_data
payload: {"timer":"1","alert":"0","duration":"4 minutes 32 seconds"}

then go to HA and check
 - no errors in the logs
 - check sensors (from development tools link)

**Comment by proddy** [comment] 2019-10-15 15:34
ok - will double check the config tonight.

**Comment by proddy** [comment] 2019-10-15 15:44
in sensors.yaml

```
- platform: mqtt
  name: 'Last shower duration'
  state_topic: "home/ems-esp/shower_data"
  value_template: "{{ value_json.duration }}"
  force_update: true
```

**Comment by mrfixit1** [comment] 2019-10-15 16:47
It's fixed, thanks. Verified OK by both running the shower for >2 mins and publishing test mqtt packages.

**Comment by majdzik84** [comment] 2019-10-16 10:34
> Fix verified OK: switching thermostat modes now works well, the mode name and symbols under the thermostat dial in the UI are correct and the dial colour changes between green for auto and orange for heat (i.e. manual). The lights on my RC20 change immediately, although the web UI on my Android phone needs a few seconds to catch up - I guess this is inherent. Thanks for the speedy updates.
> 
@ Proddyis there a chance that RC35 will also work correctly on the thermostat in ha? for me the automatic mode is always selected (green circle) even if it is heat and it should be orange.
The buttons work correctly (switch states) but do not show the current one - they are always gray
If the RC20 succeeded, it can also be RC35?

![image](https://user-images.githubusercontent.com/31352476/66911605-26592f00-f011-11e9-97ff-9a131cddd9c9.png)

**Comment by proddy** [comment] 2019-10-16 10:48
I don't have an RC35 so its hard to test. It seems like the incoming MQTT are not mapped correctly. Check the climate.yaml and also experiment with sending test MQTT messages to find what the correct values should be. See the Wiki [here](https://github.com/proddy/EMS-ESP/wiki/MQTT) for the correct format to use. For example from HA (MQTT Explorer) send:

```
topic: home/ems-esp/thermostat_data
payload: {{"hc1":{"seltemp":15,"currtemp":20.6,"mode":"auto"}}
```
and see what happens. The mode should match the climate.yaml and valid settings are “auto”, “off”, “cool”, “heat”, “dry”, “fan_only” as specified in https://www.home-assistant.io/integrations/climate.mqtt.

For example using "off" should make it go nice and orange.

if there is a change needed in the code, let me know.

**Comment by majdzik84** [comment] 2019-10-16 10:59
I think the climate.yaml is correct. 
I noticed that when switching to heat (day) or off (night) mode, HA returns an error in logs

> Invalid modes mode: day
> 12:57 components/mqtt/climate.py (ERROR)
> Invalid modes mode: night
> 12:57 components/mqtt/climate.py (ERROR) - message first occured at 12:56 and shows up 2 times

```
  - platform: mqtt
    name: Thermostat
    modes:
      - "auto"
      - "heat"
      - "off"

    mode_state_topic: "home/ems-esp/thermostat_data"
    current_temperature_topic: "home/ems-esp/thermostat_data"
    temperature_state_topic: "home/ems-esp/thermostat_data"

    temperature_command_topic: "home/ems-esp/thermostat_cmd_temp2"
    mode_command_topic: "home/ems-esp/thermostat_cmd_mode2"

    mode_state_template: "{{ value_json.hc2.mode }}"
    current_temperature_template: "{{ value_json.hc2.currtemp }}"
    temperature_state_template: "{{ value_json.hc2.seltemp }}"

    temp_step: 0.5
```

**Comment by proddy** [comment] 2019-10-16 11:34
Then the code logic is incorrect. For the RC35 it works like:

mode 0 low -> send off
mode 1 manual -> send heat
mode 2 auto -> send auto
mode 3 night -> send night
mode 4 day -> send day

I guess it should be just auto, heat and off. What should happen with day and night ?

**Comment by majdzik84** [comment] 2019-10-16 11:45
It worked correctly some time ago. maybe there were some changes.

day and night display the correct setpoint temperature.
In home assistant heat change day temp, off change night temp.

**Comment by majdzik84** [comment] 2019-10-16 11:56
in HA thermostat i have only auto, heat and off

**Comment by proddy** [comment] 2019-10-16 12:50
ok, mapped day->heat and night->off

**Comment by majdzik84** [comment] 2019-10-16 12:59
super - thermostat now works correctly. Thanx
![image](https://user-images.githubusercontent.com/31352476/66921432-75a95a80-f025-11e9-9820-31e59471a9f2.png)

**Closed** 2019-10-16 13:18 UTC
Labels: question
