### ISSUE TITLE
ESP32 reset loop in B1 and B2 firmware

### ISSUE THREAD

**Issue by sq4bja** [proddy/EMS-ESP#610] opened 2020-11-14 20:10 UTC
Hi,
In my ESP32 from firmware 2.1.1b1 I`m getting reset loop. I tested b1 and b2. In b0 everything works good.  The reset loop stops when I disconnect the ems bus. 
I have Buderus GB072 and RC310 thermostat.
Tom

**Comment by Bartekn86** [comment] 2020-11-14 21:33
have same issiue gb072 rc310

**Comment by proddy** [comment] 2020-11-14 21:52
its working on my setup so looks like something related to the thermostat changes perhaps. @MichaelDvP what do you think?

**Comment by sq4bja** [comment] 2020-11-14 21:55
We both have RC310 models. Maybe this is the reason?

**Comment by proddy** [comment] 2020-11-14 22:09
does it happen when you're in console? There is a problem with the debug logging causing weird things which I'm looking into

**Comment by sq4bja** [comment] 2020-11-14 22:13
No. This happens immediately after starting. As soon as EMS-ESP receives the telegrams. After 5-20 seconds, a restart takes place. I can see a flashing LED in ESP32 and also uptime in EMS-ESP panel. After several minutes, ESP32 stops responding.

**Comment by MichaelDvP** [comment] 2020-11-15 08:46
Is it related to HA-discovery? Have you tried with single/nested mqtt format? 
I tested with esp32 and GB125/RC35 and it work. I also switched the different formats, no crash.
I thinks GB125 have some values less than GB072, but RC35 have some more than RC310 for now.

**Comment by proddy** [comment] 2020-11-15 09:14
that's a good point. Start EMS-ESP without the EMS bus connected, go to Web and disable MQTT and see if it still crashes. I will help narrow down the root cause.

**Comment by sq4bja** [comment] 2020-11-15 13:36
Did not help. I turned off MQTT and upgraded to B2. After restart, problems with reading EMS bus again and continuous restarts. I'm going back to B0.

**Comment by proddy** [comment] 2020-11-15 13:47
damn. Are you able to compile and build the firmware yourself? There's one more thing we can try

**Comment by sq4bja** [comment] 2020-11-15 13:49
Yes, I can try.

**Comment by proddy** [comment] 2020-11-15 14:01
I'll build a test case to simulate this. What is the device_id and product_id for your GB072?

**Comment by sq4bja** [comment] 2020-11-15 14:06
![obraz](https://user-images.githubusercontent.com/26671657/99186962-2c5d9a00-2754-11eb-9efb-e1a30cbb3517.png)

**Comment by proddy** [comment] 2020-11-15 14:25
I made a test to see if I reproduce the crash in offline mode (not connected to the EMS bus), using the URL http://ems-esp/api?device=system&cmd=test&data=general2. But doesn't crash, so not sure what is causing it. I need more data!

**Comment by sq4bja** [comment] 2020-11-15 15:18
OK, below listing of telegrams send before reset EMS-ESP:
```
┌───────────────────────────────────────────
│ EMS-ESP version 2.1.1b2                  │
│ https://github.com/proddy/EMS-ESP        │
│                                          │
│ type help to show available commands     │
└──────────────────────────────────────────┘

ems-esp:/$ watch on
Watching incoming telegrams, displayed in decoded format
000+00:00:09.549 N 0: [emsesp] Thermostat(0x10) -> Me(0x0B), RC300Set(0x2BC), data: FF 2E 2A 26 1E 03 00 FF FF 00 2A 01 E1 20 01 0F 05 00 00 01 22
000+00:00:09.628 N 1: [emsesp] Boiler(0x08) -> All(0x00), UBAMonitorFast(0x18), data: 05 01 8C 00 00 00 00 80 40 80 00 01 9D 80 00 00 00 FF 30 48 00 CB 00 00 00
000+00:00:09.895 N 2: [emsesp] Boiler(0x08) -> All(0x00), MC10Status(0x2A), data: 00 00 00 00 00 00 00 00 CF 00 00 80 00 00 80 00 80 00 80 00 00
000+00:00:10.127 N 3: [emsesp] Boiler(0x08) -> All(0x00), UBAMonitorWW(0x34), data: 2F 01 9D 01 9D 01 00 05 03 00 01 08 45 00 0D 00 00 80 00
000+00:00:10.437 N 4: [emsesp] Thermostat(0x10) -> Me(0x0B), RC300Summer(0x2AF), data: 04 28 00 00 30 2D 0A 01 18 1E 00
000+00:00:10.906 N 5: [emsesp] Thermostat(0x10) -> Me(0x0B), RC300Summer(0x2B0), data: 03 28 00 00 4B 2D 11 01 19 1E 00
000+00:00:11.259 N 6: [emsesp] Thermostat(0x10) -> Me(0x0B), RC300Summer(0x2B1), data: 03 28 00 00 4B 2D 11 01 19 1E 00
000+00:00:12.134 N 7: [emsesp] Thermostat(0x10) -> Me(0x0B), RC300Summer(0x2B2), data: 03 28 00 00 4B 2D 11 01 19 1E 00
ems-esp:/$

```

**Comment by sq4bja** [comment] 2020-11-15 15:44
And here is log all
```
ems-esp:/$ log all
Log level = all
000+00:00:08.928 D 0: [telegram] Sending read Tx [#0], telegram: 0B 88 07 00 20 A8
000+00:00:12.584 D 1: [telegram] Sending read Tx [#1], telegram: 0B 88 07 00 20 A8
000+00:00:12.659 D 2: [emsesp] Last Tx read successful
000+00:00:12.659 D 3: [emsesp] New EMS device detected with ID 0x08. Requesting version information.
000+00:00:12.659 D 4: [telegram] Tx read request to device 0x08 for type ID 0x02
000+00:00:12.659 D 5: [emsesp] New EMS device detected with ID 0x09. Requesting version information.
000+00:00:12.659 D 6: [telegram] Tx read request to device 0x09 for type ID 0x02
000+00:00:12.659 D 7: [emsesp] New EMS device detected with ID 0x10. Requesting version information.
000+00:00:12.659 D 8: [telegram] Tx read request to device 0x10 for type ID 0x02
000+00:00:12.785 D 9: [emsesp] New EMS device detected with ID 0x08. Requesting version information.
000+00:00:12.785 D 10: [telegram] Tx read request to device 0x08 for type ID 0x02
000+00:00:12.785 D 11: [emsesp] New EMS device detected with ID 0x09. Requesting version information.
000+00:00:12.785 D 12: [telegram] Tx read request to device 0x09 for type ID 0x02
000+00:00:12.785 D 13: [emsesp] New EMS device detected with ID 0x10. Requesting version information.
000+00:00:12.785 D 14: [telegram] Tx read request to device 0x10 for type ID 0x02
000+00:00:12.982 D 15: [telegram] Sending read Tx [#2], telegram: 0B 88 02 00 20 BC
000+00:00:13.027 D 16: [emsesp] Last Tx read successful
000+00:00:13.027 D 17: [emsesp] Adding new device GBx72/Trendline/Cerapur/Greenstar Si/27i (device ID 0x08, product ID 123, version 06.08)
000+00:00:13.027 D 18: [boiler] Adding new Boiler with device ID 0x08
000+00:00:13.027 D 19: [emsesp] Fetching values for device ID 0x08
000+00:00:13.027 D 20: [telegram] Tx read request to device 0x08 for type ID 0x14
000+00:00:13.027 D 21: [telegram] Tx read request to device 0x08 for type ID 0x16
000+00:00:13.027 D 22: [telegram] Tx read request to device 0x08 for type ID 0x19
000+00:00:13.027 D 23: [telegram] Tx read request to device 0x08 for type ID 0x33
000+00:00:13.027 D 24: [telegram] Tx read request to device 0x08 for type ID 0xE6
000+00:00:13.027 D 25: [telegram] Tx read request to device 0x08 for type ID 0xEA
000+00:00:13.356 D 26: [telegram] Sending read Tx [#3], telegram: 0B 89 02 00 20 B4
000+00:00:13.392 D 27: [emsesp] Last Tx read successful
000+00:00:13.392 D 28: [emsesp] Adding new device BC25 (device ID 0x09, product ID 125, version 03.03)
000+00:00:13.392 D 29: [emsesp] Fetching values for device ID 0x09
000+00:00:13.654 D 30: [telegram] Sending read Tx [#4], telegram: 0B 90 02 00 20 7C
000+00:00:13.718 D 35: [telegram] Tx read request to device 0x10 for type ID 0x2A6
000+00:00:13.718 D 36: [telegram] Tx read request to device 0x10 for type ID 0x2A7
000+00:00:13.718 D 37: [telegram] Tx read request to device 0x10 for type ID 0x2A8
000+00:00:13.718 D 38: [telegram] Tx read request to device 0x10 for type ID 0x2B9
000+00:00:13.718 D 39: [telegram] Tx read request to device 0x10 for type ID 0x2BA
000+00:00:13.718 D 40: [telegram] Tx read request to device 0x10 for type ID 0x2BB
000+00:00:13.718 D 41: [telegram] Tx read request to device 0x10 for type ID 0x2BC
000+00:00:13.718 D 42: [telegram] Tx read request to device 0x10 for type ID 0x2AF
000+00:00:13.718 D 43: [telegram] Tx read request to device 0x10 for type ID 0x2B0
000+00:00:13.718 D 44: [telegram] Tx read request to device 0x10 for type ID 0x2B1
000+00:00:13.718 D 45: [telegram] Tx read request to device 0x10 for type ID 0x2B2
000+00:00:13.718 D 46: [telegram] Tx read request to device 0x10 for type ID 0x29B
000+00:00:13.718 D 47: [telegram] Tx read request to device 0x10 for type ID 0x29C
000+00:00:13.718 D 48: [telegram] Tx read request to device 0x10 for type ID 0x29D
000+00:00:13.718 D 49: [telegram] Tx read request to device 0x10 for type ID 0x29E
000+00:00:13.718 D 50: [emsesp] Fetching values for device ID 0x10
000+00:00:13.718 D 51: [telegram] Tx read request to device 0x10 for type ID 0x2F5
000+00:00:13.718 D 52: [telegram] Tx read request to device 0x10 for type ID 0x31B
000+00:00:13.718 D 53: [telegram] Tx read request to device 0x10 for type ID 0x23A
000+00:00:13.718 D 54: [telegram] Tx read request to device 0x10 for type ID 0x240
000+00:00:14.052 D 55: [telegram] Sending read Tx [#14], telegram: 0B 90 FF 00 20 01 A5 19
000+00:00:14.184 D 56: [emsesp] Last Tx read successful
000+00:00:14.184 D 57: [emsesp] Received RC300Monitor
000+00:00:14.184 D 58: [emsesp] Toggling fetch for device ID 0x10, telegram ID 0x2A5 to 1
000+00:00:14.184 D 59: [emsesp] Toggling fetch for device ID 0x10, telegram ID 0x2B9 to 1
000+00:00:14.301 D 60: [emsesp] Received RC300Floordry
000+00:00:14.559 D 61: [emsesp] Received RC300Monitor
000+00:00:14.948 D 62: [telegram] Sending read Tx [#34], telegram: 0B 90 FF 19 20 01 A5 D1
000+00:00:15.057 D 63: [emsesp] Last Tx read successful
000+00:00:15.057 D 64: [emsesp] Received RC300Monitor
000+00:00:15.142 D 65: [emsesp] Received RC300Monitor
000+00:00:15.349 D 66: [emsesp] Received RC300WWmode2
000+00:00:15.796 D 67: [telegram] Sending read Tx [#15], telegram: 0B 90 FF 00 20 01 A6 1A
000+00:00:16.164 D 68: [emsesp] Received UBAMonitorFast
000+00:00:16.433 D 69: [emsesp] Received MC10Status
000+00:00:16.640 D 70: [emsesp] Received UBAMonitorWW
000+00:00:16.865 D 71: [telegram] Sending read Tx [#35], telegram: 0B 90 FF 00 20 01 A6 1A
000+00:00:16.911 D 72: [emsesp] Last Tx read successful
000+00:00:16.911 D 73: [emsesp] This telegram (RC300Monitor) is not recognized by the EMS bus
000+00:00:16.911 D 74: [emsesp] Toggling fetch for device ID 0x10, telegram ID 0x2A6 to 0
000+00:00:16.911 D 75: [emsesp] No telegram type handler found for ID 0x2A6 (src 0x10)
000+00:00:17.336 D 76: [telegram] Sending read Tx [#16], telegram: 0B 90 FF 00 20 01 A7 1B
000+00:00:17.380 D 77: [emsesp] Last Tx read successful
000+00:00:17.380 D 78: [emsesp] This telegram (RC300Monitor) is not recognized by the EMS bus
000+00:00:17.380 D 79: [emsesp] Toggling fetch for device ID 0x10, telegram ID 0x2A7 to 0
000+00:00:17.380 D 80: [emsesp] No telegram type handler found for ID 0x2A7 (src 0x10)
000+00:00:17.711 D 81: [telegram] Sending read Tx [#17], telegram: 0B 90 FF 00 20 01 A8 14
000+00:00:17.759 D 82: [emsesp] Last Tx read successful
000+00:00:17.759 D 83: [emsesp] This telegram (RC300Monitor) is not recognized by the EMS bus
000+00:00:17.759 D 84: [emsesp] Toggling fetch for device ID 0x10, telegram ID 0x2A8 to 0
000+00:00:17.759 D 85: [emsesp] No telegram type handler found for ID 0x2A8 (src 0x10)
000+00:00:18.033 D 86: [telegram] Sending read Tx [#18], telegram: 0B 90 FF 00 20 01 B9 05
000+00:00:18.153 D 87: [emsesp] Last Tx read successful
000+00:00:18.153 D 88: [emsesp] Received RC300Set
000+00:00:18.481 D 89: [telegram] Sending read Tx [#19], telegram: 0B 90 FF 00 20 01 BA 06
000+00:00:18.601 D 90: [emsesp] Last Tx read successful
000+00:00:18.601 D 91: [emsesp] Received RC300Set
000+00:00:18.601 D 92: [emsesp] Toggling fetch for device ID 0x10, telegram ID 0x2A6 to 0
000+00:00:18.601 D 93: [emsesp] Toggling fetch for device ID 0x10, telegram ID 0x2BA to 0
000+00:00:18.904 D 94: [telegram] Sending read Tx [#20], telegram: 0B 90 FF 00 20 01 BB 07
000+00:00:19.024 D 95: [emsesp] Last Tx read successful
000+00:00:19.024 D 96: [emsesp] Received RC300Set
000+00:00:19.024 D 97: [emsesp] Toggling fetch for device ID 0x10, telegram ID 0x2A7 to 0
000+00:00:19.024 D 98: [emsesp] Toggling fetch for device ID 0x10, telegram ID 0x2BB to 0
000+00:00:19.378 D 99: [telegram] Sending read Tx [#21], telegram: 0B 90 FF 00 20 01 BC 00
000+00:00:19.497 D 100: [emsesp] Last Tx read successful
000+00:00:19.497 D 101: [emsesp] Received RC300Set
000+00:00:19.497 D 102: [emsesp] Toggling fetch for device ID 0x10, telegram ID 0x2A8 to 0
000+00:00:19.497 D 103: [emsesp] Toggling fetch for device ID 0x10, telegram ID 0x2BC to 0
000+00:00:19.725 D 104: [telegram] Sending read Tx [#22], telegram: 0B 90 FF 00 20 01 AF 13
000+00:00:19.813 D 105: [emsesp] Last Tx read successful
000+00:00:19.813 D 106: [emsesp] Received RC300Summer
000+00:00:20.223 D 107: [telegram] Sending read Tx [#23], telegram: 0B 90 FF 00 20 01 B0 0C
000+00:00:20.303 D 108: [emsesp] Last Tx read successful
000+00:00:20.303 D 109: [emsesp] Received RC300Summer
000+00:00:20.621 D 110: [telegram] Sending read Tx [#24], telegram: 0B 90 FF 00 20 01 B1 0D
000+00:00:20.708 D 111: [emsesp] Last Tx read successful
000+00:00:20.708 D 112: [emsesp] Received RC300Summer
000+00:00:20.969 D 113: [telegram] Sending read Tx [#25], telegram: 0B 90 FF 00 20 01 B2 0E
000+00:00:21.052 D 114: [emsesp] Last Tx read successful
000+00:00:21.052 D 115: [emsesp] Received RC300Summer
000+00:00:21.392 D 116: [telegram] Sending read Tx [#26], telegram: 0B 90 FF 00 20 01 9B 27
ems-esp:/$

```

**Comment by MichaelDvP** [comment] 2020-11-15 16:06
Ah, i see the error, forgot to add heatingcurve_ids to heating_circuit serach. I'll fix it.

**Comment by Bartekn86** [comment] 2020-11-15 16:07
thank you

**Comment by MichaelDvP** [comment] 2020-11-15 16:49
Please check if it is fixed now or something other to search for.

**Comment by sq4bja** [comment] 2020-11-15 16:57
Ok. It was that... Now everyfing works perfectly.
Thank You!

**Comment by Bartekn86** [comment] 2020-11-15 18:07
all ok thank you

**Closed** 2020-11-15 18:32 UTC
Labels: bug
