### ISSUE TITLE
Gate restart when trying to change temperatures - 1.9.5b17

### ISSUE THREAD

**Issue by majdzik84** [proddy/EMS-ESP#298] opened 2020-01-14 15:50 UTC
When I change the room / water temperature in HA, the gate restarts. There is no information in telnet - it simply disconnects. The temperature remains unchanged.

**Comment by proddy** [comment] 2020-01-14 16:34
Thanks for reporting. I'll look into it. I've also heard reports of the latest 1.9.5 of not always detecting EMS devices.

**Comment by proddy** [comment] 2020-01-14 20:47
I tested this on 1.9.5b17 and can't reproduce. Does it always happen? Does it happen if you publish MQTT commands? Or if you try the same from Telnet commands?

**Comment by majdzik84** [comment] 2020-01-14 22:56
I don't think it happens every time. (I tested it before and it seemed that every time) I just raised the temperature and it was set correctly.

-The problem (restart) usually occurs when I set the temperature
- I also noticed restart in telnet but not so often.

After restart, the situation returned and I noticed that it does not give set temp. And current temp.

![1](https://user-images.githubusercontent.com/31352476/72388063-46d67980-3725-11ea-8ed1-d3bf2ca06d84.jpg)

sometimes I also see
![image](https://user-images.githubusercontent.com/31352476/72388405-24912b80-3726-11ea-99d2-c9c524a66f40.png)

**Comment by proddy** [comment] 2020-01-19 11:01
@majdzik84 lets focus on the thermostat readings issue. Are you saying after a restart HC2 is shown correctly and then you get wrong values? Is it just the Mode?

**Comment by majdzik84** [comment] 2020-01-19 12:30
At this point, I see what below:
![image](https://user-images.githubusercontent.com/31352476/72680872-0416f780-3abf-11ea-9fc7-6d66e392923d.png)

At this point, I see what below:

Note that this is night (off) mode.
How do I change the mode to e.g. DAY (heat)

![image](https://user-images.githubusercontent.com/31352476/72680957-a1722b80-3abf-11ea-8184-946d28e0f097.png)

Unfortunately, when the temperature changes, the gate restarts

**Comment by proddy** [comment] 2020-01-19 13:51
Could you create a new issue for the HC2 mode issue, and lets leave this to the crashes.

On the crashes: I just can't reproduce so need to work with you on a test case that always fails
On the modes: I need some example telegrams for 0x47 and 0x48 (this is HC2 on RC35) to see why the data is missing.

**Comment by proddy** [comment] 2020-01-28 20:29
@majdzik84 are you still experiencing restarts when changing temperatures via MQTT and the Telnet client?

**Comment by majdzik84** [comment] 2020-01-28 22:51
@proddy Unfortunately, restarts still occur at every temperature change by mqtt.

Telnet did not cause any restart during 30 attempts to change temperatures and modes

**Comment by proddy** [comment] 2020-01-31 10:28
@majdzik84 can you post the MQTT command you are sending? We need to trace where in the code its crashing

**Comment by majdzik84** [comment] 2020-01-31 16:57
@proddy mqtt command is sent by Home assistant 0.104.3. how can i get them ??

**Comment by proddy** [comment] 2020-01-31 17:07
try and reproduce with Telnet. Then I know if the bug is in the core code or the mqtt code. Open a telnet and do something like `thermostat temp 22`  or `thermostat temp 2 22` for HC2. We're just trying to make it crash

**Comment by majdzik84** [comment] 2020-01-31 23:23
Change in telenet did not cause restart (10 changes - 0 restarts)
A change in HA always causes a restart. (10 changes - 10 restarts)

**Comment by proddy** [comment] 2020-02-01 07:52
can you use something like MQTT explorer to capture the MQTT that is being sent from HA?

**Comment by majdzik84** [comment] 2020-02-01 14:35
I don't know where I can get the specific mqtt command. Will this screen help? I just changed the HC2 temperature to 21.5C

![image](https://user-images.githubusercontent.com/31352476/73593791-2457a500-4508-11ea-8775-9edc023684d1.png)

**Comment by MichaelDvP** [comment] 2020-02-01 17:38
use **thermostat_cmd_temp2 21.5** to change the temperature, only insert the temperature in °C 
I don't know why mqtt-explorer does not show the other cmd-subscriptions, but also writing a wrong, but valid, json to writeable commands like thermostat_cmd affects a restart. 
**thermostat_cmd {"cmd":"temp2","data":21}** 
works as expected.
**thermostat_cmd {"hc2":{"temp": 21}}**
or something else restarts the ems-esp.
double-check the wiki to send valid commands.

**Comment by proddy** [comment] 2020-02-02 10:43
thanks @MichaelDvP for pointing out the error (again). I'm fixing it now

**Comment by proddy** [comment] 2020-02-02 11:23
fixed. @majdzik84 you shouldn't see any crashes anymore. But I think the problem is your Home Assistant configuration as it looks like you're sending the wrong topics. See https://emsesp.github.io/docs/#/Home-Assistant

**Comment by majdzik84** [comment] 2020-02-02 13:21
@proddy   unfortunately the patch doesn't work for me :(
My HA configuration is exactly like in the wiki. In version 1.9.4b10, these settings worked correctly.


```
  - platform: mqtt
    name: Parter
    modes:
      - "auto"
      - "heat"
      - "off"

    mode_state_topic: "home/ems-esp/thermostat_data"
    current_temperature_topic: "home/ems-esp/thermostat_data"
    temperature_state_topic: "home/ems-esp/thermostat_data"

    temperature_command_topic: "home/ems-esp/thermostat_cmd_temp2"
    mode_command_topic: "home/ems-esp/thermostat_cmd_mode2"


    mode_state_template: "{% if value_json.hc2.mode == 'manual' %} heat {% else %} {{value_json.hc2.mode}} {% endif %}"
    current_temperature_template: "{{ value_json.hc2.currtemp }}"
    temperature_state_template: "{{ value_json.hc2.seltemp }}"

    temp_step: 0.5

```

**Comment by proddy** [comment] 2020-02-02 13:57
oh that's not good. Ok, one more try.

- Telnet to EMS-ESP. You don't logging on for this.
- Use your MQTT Explorer and Publish the Topic `home/ems-esp/thermostat_cmd_temp2` with a value of 20 (use raw or json)

You should see `"Setting new thermostat temperature to 20.0 for heating circuit 2 type 0 (0=auto,1=night,2=day,3=holiday)"` in the Telnet window, and no crashes.

does that work?

**Comment by majdzik84** [comment] 2020-02-02 14:16
Did not work.
The temperature change information is not displayed (gate restart)

**Comment by proddy** [comment] 2020-02-02 17:48
very strange. I'll keep investigating.

**Comment by proddy** [comment] 2020-02-02 21:51
can't figure out what it's failing. Can you try other commands directly from MQTT Explorer, like
topic: `home/ems-esp/thermostat_cmd_mode2` payload:`auto` as JSON or raw
or
topic: `home/ems-esp/thermostat_cmd` payload:`{"cmd":"temp2", "data": 20}` as JSON

if any of those cause a crash I'm out of ideas and will need to send a special firmware version with additional debug logs to trace.

**Comment by majdzik84** [comment] 2020-02-03 07:52
After entering the above commands, the changes worked as they should and there was no restart

**Comment by majdzik84** [comment] 2020-02-03 08:04
@proddy. I also tried now  `home/ems-esp/thermostat_cmd_temp2 with a value of 20 ` and it worked !
I started looking for differences and I think I found situations when the command did not work properly.

### Look: **There is no Mixing module data in telnet:**

![correct](https://user-images.githubusercontent.com/31352476/73635352-a1e3f800-4663-11ea-9133-c7c0a7ab6569.png)


When I reset the gate in telnet, I see the **Mixing module data: and now I can't change the temperature** because the gate restart appears.
![corr2](https://user-images.githubusercontent.com/31352476/73635481-f12a2880-4663-11ea-8889-8445d5428e4e.png)

**Comment by proddy** [comment] 2020-02-03 11:30
I can't remember - do you have a mixing module at all?

**Comment by majdzik84** [comment] 2020-02-03 12:07
Yes,I have MM10 module

**Comment by proddy** [comment] 2020-02-03 15:30
ok, so without the MM10 showing up you can set the temp. But with the MM10 recognized it crashes the system? Very strange!

**Comment by majdzik84** [comment] 2020-02-03 17:48
Yes. This is how it looks. In the earlier case, when MM10 could not be detected, I could change the temperature successfully. (In 1.9.4b10 - it has never detected MM10 yet, that's why I haven't experienced it before).

I just tried to change the temperature of hot water and despite the detection of MM10 it turned into a telenet one time, an error popped up and the gate reset (I don't know if it will help)

![image](https://user-images.githubusercontent.com/31352476/73676324-7e956900-46b4-11ea-9273-d2f84d973056.png)

**Comment by proddy** [comment] 2020-02-03 22:17
ok, I'll look into the MM10. The piece of code was written by someone else so I need to check what could be causing it.

**Comment by proddy** [comment] 2020-02-03 22:31
I'll need to create a dev build for you with some extra debug. Are you ok to compile and upload yourself or would you prefer receiving the firmware bin files?

**Comment by majdzik84** [comment] 2020-02-03 22:42
if I can, please .bin

**Comment by proddy** [comment] 2020-02-08 14:24
ok, try this [bin](https://github.com/proddy/EMS-ESP/releases/download/travis-dev-build/EMS-ESP-1_9_5b29-d1_mini-noMM.bin) file. I've removed the Mixer code. Please try both telnet and MQTT commands and see if it crashes. If it does, great, we know where to look...

thanks for helping out

**Comment by majdzik84** [comment] 2020-02-08 20:50
@proddy , It looks like the mixer is causing the problem. Now everything works fine (mqtt and telenet did not cause any restart)

**Comment by proddy** [comment] 2020-02-08 20:52
great! I'll start debugging...

**Comment by proddy** [comment] 2020-02-08 21:38
new version available, same filename. this time it will capture the mixing data but not publish to MQTT. see if this one crashes...

**Comment by majdzik84** [comment] 2020-02-09 11:52
Works correctly. No resets

**Comment by proddy** [comment] 2020-02-09 12:08
cool. and if you type `info` does it show Mixer information?

**Comment by majdzik84** [comment] 2020-02-09 12:31
Yes. information is displayed.
![image](https://user-images.githubusercontent.com/31352476/74101996-afa3ec80-4b3f-11ea-8ff6-8539e933abae.png)


I noticed that there was a bug in boiler temperature (jump temp.)
![image](https://user-images.githubusercontent.com/31352476/74102065-57211f00-4b40-11ea-838d-fdb40a1a5bc9.png)
![image](https://user-images.githubusercontent.com/31352476/74102069-63a57780-4b40-11ea-9e27-520fbf6db65d.png)

**Comment by proddy** [comment] 2020-02-09 12:38
what happened with the boiler temp exactly?

**Comment by proddy** [comment] 2020-02-09 13:31
ok, new version - this time with MQTT. let me know if it crashes!

**Comment by majdzik84** [comment] 2020-02-09 14:56
Unfortunately there are restarts again. 
Sometimes, after restarting, it is possible to change the temperature once and an error is displayed
```
Setting new thermostat temperature to 21.50 for heating circuit 2 type 0 (0=auto                 ,1=night,2=day,3=holiday)
[MQTT] Error publishing to home/ems-esp/mixing_data with payload {"hc2":{"flowTe                 mp":25.8,"setflowTemp":22,"pumpMod":100}} [error 0]
```


Boiler temperature suddenly changes values ​​from e.g. 40C to 15C.
![image](https://user-images.githubusercontent.com/31352476/74104382-7164f800-4b54-11ea-85cc-c54c0be095ea.png)

**Comment by proddy** [comment] 2020-02-09 16:46
Ok, I think I have a fix for the boiler temp. It's a clash with some Bosch logic I added a while back.

As for the MM10, I need some example telegrams to replicate the error. Are you able to capture 1 or 2 telegrams of type 0x01D8 and 0xAB for me?

**Comment by proddy** [comment] 2020-02-09 18:25
fix for boiler temp in https://github.com/proddy/EMS-ESP/releases/download/travis-dev-build/EMS-ESP-1_9_5b30-d1_mini-noMM.bin

**Comment by majdzik84** [comment] 2020-02-09 19:28
I was only able to capture the 0xAB telegram by entering log v (should I use another command for ?)
```
(20:14:31) Mixing Module -> All, type 0xAB, telegram: 21 00 AB 00 1C 01 17 64 FC 01 00 (CRC=58) #data=7
(20:15:30) Mixing Module -> All, type 0xAB, telegram: 21 00 AB 00 1C 01 1C 64 F9 01 00 (CRC=FC) #data=7
(20:16:30) Mixing Module -> All, type 0xAB, telegram: 21 00 AB 00 1C 01 1D 64 FA 01 00 (CRC=E0) #data=7
(20:17:30) Mixing Module -> All, type 0xAB, telegram: 21 00 AB 00 1C 01 1F 64 F9 01 00 (CRC=CC) #data=7
```

**Comment by proddy** [comment] 2020-02-09 19:39
that's fine. I can simulate the MM10 data with your 0xAB example. But I don't get any crashes so the problem is elsewhere.

**Comment by MichaelDvP** [comment] 2020-02-10 11:05
I don't know if it helps. In my system there is also RC35 and MM10, but a different boiler and i do not use HA, i have ioBroker running on a raspberry with ioBroker-mqtt-server.
I can set temperatures, circulation, etc, via mqtt without restart and the system seems stable, but today i realized a unexpected restart 2 days ago.
```
[APP] EMS-ESP version: 1.9.5b28
[APP] MyESP version: 1.2.26
[APP] Build timestamp: 2020-02-04 08:58:56
[APP] Uptime: 1 day 20 hours 15 minutes 15 seconds
[SYSTEM] Last reset reason: Hardware Watchdog
[SYSTEM] Last reset info: Fatal exception:4 flag:1 (WDT) epc1:0x40000f68 epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000
```
At the time of the restart (08.02.2020-12:25) i was updating the raspberry and some ioBroker adapters, and rebooted the raspberry afterwards. 
I tried to trigger a restart by disable MQTT-Server, but i get:
```
[MQTT] TCP Disconnected
[MQTT] Disconnected! (count 1)
[MQTT] Connecting to MQTT...
[MQTT] TCP Disconnected
[MQTT] Disconnected! (count 2)
...
[MQTT] Disconnected! (count 15)
[MQTT] Connecting to MQTT...
[MQTT] MQTT connected
Setting new thermostat temperature to 21.0 for heating circuit 2 type 0 (0=auto,1=night,2=day,3=holiday)
Setting boiler warm water circulation off
```
a restart of the raspberry gives the same result, no restart of ems-esp. 
A full protocol is attached (for mqtt-settings etc. btw: i missed the ntp-server-setting in terminal)

A hour ago i updated and rebooted my wifi-router and ems-esp crashes to.
```
 [SYSTEM] Last reset reason: Exception
 [SYSTEM] Last reset info: Fatal exception:9 flag:2 (EXCEPTION) epc1:0x401053a0 epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000003 depc:0x00000000
```
But i can't say what exactly triggers the ems-esp-restart.

[20200210_084047_EMS.log](https://github.com/proddy/EMS-ESP/files/4180374/20200210_084047_EMS.log)

**Comment by proddy** [comment] 2020-02-11 19:18
I still don't know what is causing the crashes. I'm hoping that someone else will bump into this problem so I can triangulate. Thanks @MichaelDvP for providing the feedback

**Comment by majdzik84** [comment] 2020-02-11 20:03
ok, in that case i'm coming back to the version you shared earlier without mixer data, hoping that in the future it will be resolved.

**Comment by proddy** [comment] 2020-02-11 20:09
@majdzik84 one thing we could try is if you just leave logging on for 2 minutes (full verbose) and I use that to simulate your setup and watch for the crash. I've looked through the Mixing code and can't see why it would cause a crash, but then it always ends up being something really obvious

**Comment by majdzik84** [comment] 2020-02-11 20:26
@proddy  I'm sending logs :)

[logs.txt](https://github.com/proddy/EMS-ESP/files/4188127/logs.txt)

**Comment by proddy** [comment] 2020-02-11 20:28
oh, well there goes my evening ! :-)

**Comment by MichaelDvP** [comment] 2020-02-12 07:33
@majdzik84 you are publishing very often. Maybe it's not the mixer, but the more payload in short time which overloads the server and causes the reboots. Have you tried to set publish_time to a larger value (i use 60 sec).

**Comment by proddy** [comment] 2020-02-12 07:57
well spotted ! Yes looks like publish time is 5?

**Comment by majdzik84** [comment] 2020-02-12 08:46
yes, the time was set to 5sec. I changed to 60 sec but there are no changes. Still restarts

**Comment by proddy** [comment] 2020-02-12 13:15
@majdzik84 I used your data and still couldn't crash EMS-ESP. Two more things you could try:
- leave verbose logging on, send a command via MQTT and when it crashes send me the log so I can see the last known operation

**Comment by majdzik84** [comment] 2020-02-12 13:42
that's what i did last time.

```
Starting scheduled MQTT publish...
Publishing boiler data via MQTT
Publishing thermostat data via MQTT
Publishing external sensor data via MQTT
(21:23:44) UBAMaster -> All, type 0x34, telegram: 08 00 34 00 0A 00 75 00 75 00 00 00 03 00 00 00 78 00 00 3C 00 (CRC=CA) #data=17
(21:23:44) UBAMaster -> All, type 0x18, telegram: 08 00 18 00 2C 01 6D 64 00 41 01 24 62 80 00 00 75 01 65 00 00 10 36 41 00 E3 00 02 00 (CRC=BF) #data=25

RESTART
```

**Comment by proddy** [comment] 2020-02-12 14:30
@majdzik84 made a debug version [here](https://github.com/proddy/EMS-ESP/releases/download/travis-dev-build/EMS-ESP-1_9_5b30-d1_mini-debug.bin)

**Comment by majdzik84** [comment] 2020-02-12 16:10
I have uploaded. Should I send a new log v? restart still occurs

**Comment by proddy** [comment] 2020-02-12 17:03
yes please. Just want to know what happens just before it crashes. Probably an MQTT publish?

**Comment by majdzik84** [comment] 2020-02-12 18:36
Logs [logs.txt](https://github.com/proddy/EMS-ESP/files/4194270/logs.txt)

**Comment by proddy** [comment] 2020-02-12 18:49
I was expecting to see the MQTT publish debug info too? Did you remove this or perhaps I sent you the wrong version?

**Comment by majdzik84** [comment] 2020-02-12 18:55
I didn't delete anything.
The reboot practically appeared automatically without sending mqtt. It resets all the time :)

**Comment by proddy** [comment] 2020-02-12 20:08
OMG. its getting worse. Perhaps its infected with covid-19. I'll send over a new build...

**Comment by proddy** [comment] 2020-02-15 15:35
@majdzik84 thanks for being patient. Have another build without the mixer code in it. You can download it [here](https://github.com/proddy/EMS-ESP/releases/download/travis-dev-build/EMS-ESP-1_9_5b33-d1_mini-noMM.dev) and rename it to a .bin file and upload. See if it crashes.

**Comment by majdzik84** [comment] 2020-02-15 22:26
@proddy There are NO restarts

**Comment by proddy** [comment] 2020-02-16 16:21
and do you have `publish_time` set to `-1` to disable any MQTT ?

**Comment by majdzik84** [comment] 2020-02-16 16:37
No, I didn't set publish time before (I was 60).

After setting publish_time -1 I didn't notice any changes. Everything ok, no restart.

**Comment by proddy** [comment] 2020-02-16 16:39
ok, I just want to rule out 100% its a problem with how the Mixing data gets sent to MQTT. Could you use the latest dev build from GitHub, set publish_time to -1, reboot and see it still crashes.

**Comment by majdzik84** [comment] 2020-02-16 17:20
Ok, I tested it.
Published_time -1 has no restarts.
When I changed publish_time 60 the restarts came back

**Comment by proddy** [comment] 2020-02-16 17:38
great, this is progress. this means definitely something in the code that sends the MQTT for the Mixing. Looking into it...

**Comment by proddy** [comment] 2020-02-17 10:17
ok, another build to try [here](https://github.com/proddy/EMS-ESP/releases/download/travis-dev-build/EMS-ESP-1_9_5b34-d1_mini-noMM.xxx). This one use with MQTT publishing on. `info` should show you the mixer data but it will not send the mixing topics via MQTT. See if it crashes!

**Comment by majdzik84** [comment] 2020-02-17 11:29
its' ok, there is no crashes

**Comment by proddy** [comment] 2020-02-17 13:39
one more! https://github.com/proddy/EMS-ESP/releases/download/travis-dev-build/EMS-ESP-1_9_5b35-d1_mini.xxx

**Comment by majdzik84** [comment] 2020-02-17 15:21
This time they are restarts as soon as I change the temperature. There is no message in putty informing about temperature change, only restart immediately.

**Comment by proddy** [comment] 2020-02-17 15:29
- does the same happen if doing this from Telnet with 'thermostat temp 20'
- and does the same happen when `publish_time` is -1 ?

**Comment by majdzik84** [comment] 2020-02-17 16:08
`does the same happen if doing this from Telnet with 'thermostat temp 20`

**Yes, a temperature change message is sent and a reset occurs.**
![1](https://user-images.githubusercontent.com/31352476/74668989-9b4a9a00-51a6-11ea-8de7-4a4796fa49d9.png)

`and does the same happen when publish_time is -1 ?`

There are **no restarts** with publish_time -1

**Comment by proddy** [comment] 2020-02-17 16:54
we're getting closer! new [build](https://github.com/proddy/EMS-ESP/releases/download/travis-dev-build/EMS-ESP-1_9_5b35-d1_mini.xxx) to try.

**Comment by majdzik84** [comment] 2020-02-17 17:12
publish_time 60 - restarts  (mqtt and telenet)
publish_time -1 - NO restarts (mqtt and telenet)

**Comment by proddy** [comment] 2020-02-17 19:40
another [build](https://github.com/proddy/EMS-ESP/releases/download/travis-dev-build/EMS-ESP-1_9_5b35-d1_mini.xxx). This time with `publish_time` set. In telnet you should see some logging appear after you set the thermostat temp

**Comment by majdzik84** [comment] 2020-02-17 22:03
@proddy 

I think something is wrong with this build. After uploading, I get a message in putty "No connection can be made to the EMS bus".
After a few moments my RC35 stops working (nothing displays, nothing lights up)
![image](https://user-images.githubusercontent.com/31352476/74685869-183e3980-51d0-11ea-8d8a-911839ac3525.png)

After some time and repeated reboots of the furnace and gate I was able to test in telnet and it was ok.
Should the new build occupy 1838kb? (previous ones had about 607kb)
![image](https://user-images.githubusercontent.com/31352476/74685071-c4325580-51cd-11ea-9472-4638a9bf9946.png)

**Comment by proddy** [comment] 2020-02-17 22:09
something strange happened with the upload. I made a new .bin file. Same location with the ,xxx extension and you'll need to rename.

**Comment by majdzik84** [comment] 2020-02-17 22:19
![image](https://user-images.githubusercontent.com/31352476/74689525-c0a5cb00-51db-11ea-84fd-e4f7a124468c.png)

no reboots (with mqtt and telenet)

**Comment by proddy** [comment] 2020-02-18 09:12
ok, new build in same location. this time with MQTT publishing turned on. This will help home in on which block of code is crashing

**Comment by majdzik84** [comment] 2020-02-18 10:19
Very frequent automatic restarts. 

Once I managed to get:
```
change of temperature via telenet
Setting new thermostat temperature to 22.0 for heating circuit 2 type 0 (0=auto,1=night,2=day,3=holiday)
majdzik84: data is [{"hc2":{"flowTemp":23.9,"setflowTemp":24,"pumpMod":100}}]
[MQTT] Error publishing to home/ems-esp/mixing_data with payload {"hc2":{"flowTemp":23.9,"setflowTemp":24,"pumpMod":100}} [error 0]
[MQTT] Error publishing to home/ems-esp/sensors with payload {"28AAC6293E140173":17.88,"28AAC3273E1401B4":44.75} [error 0]
RESTART
```

**Comment by proddy** [comment] 2020-02-18 11:02
ok so something in the MQTT publishing is causing the crash and its not Mixer related. That's progress! I think the solution is to use a buffer to queue up the MQTT messages and send them out when the system is not busy to avoid any locking and also check we receive an ACK from the broker.

As a quick test can you try again with the latest .xxx file I just uploaded? Want to test something.

BTW it's great that you can upload and test so quickly. It's very helpful, thanks!

**Comment by majdzik84** [comment] 2020-02-18 12:17
If I can help with something, I am happy to do it. I don't know coding, at least I can test :)

After uploading the latest version there are no reboots but I see error:


```
majdzik84: data is [{"hc2":{"flowTemp":26.8,"setflowTemp":21,"pumpMod":100}}]
[MQTT] Error publishing to home/ems-esp/sensors with payload {"28AAC6293E140173":18,"28AAC3273E1401B4":44.13} [error 0]
majdzik84: data is [{"hc2":{"flowTemp":26.8,"setflowTemp":21,"pumpMod":100}}]
[MQTT] Error publishing to home/ems-esp/sensors with payload {"28AAC6293E140173":17.94,"28AAC3273E1401B4":44} [error 0]
majdzik84: data is [{"hc2":{"flowTemp":26.6,"setflowTemp":21,"pumpMod":100}}]
[MQTT] Error publishing to home/ems-esp/sensors with payload {"28AAC6293E140173":17.94,"28AAC3273E1401B4":43.88} [error 0]
majdzik84: data is [{"hc2":{"flowTemp":26.6,"setflowTemp":21,"pumpMod":100}}]
[MQTT] Error publishing to home/ems-esp/sensors with payload {"28AAC6293E140173":18,"28AAC3273E1401B4":43.81} [error 0]
majdzik84: data is [{"hc2":{"flowTemp":26.6,"setflowTemp":21,"pumpMod":100}}]
[MQTT] Error publishing to home/ems-esp/sensors with payload {"28AAC6293E140173":18,"28AAC3273E1401B4":43.69} [error 0]
majdzik84: data is [{"hc2":{"flowTemp":26.5,"setflowTemp":21,"pumpMod":100}}]
[MQTT] Error publishing to home/ems-esp/mixing_data with payload {"hc2":{"flowTemp":26.5,"setflowTemp":21,"pumpMod":100}} [error 0]
[MQTT] Error publishing to home/ems-esp/sensors with payload {"28AAC6293E140173":18.06,"28AAC3273E1401B4":43.63} [error 0]

Setting new thermostat temperature to 21.0 for heating circuit 2 type 0 (0=auto,1=night,2=day,3=holiday)
majdzik84: data is [{"hc2":{"flowTemp":26.5,"setflowTemp":21,"pumpMod":100}}]
[MQTT] Error publishing to home/ems-esp/mixing_data with payload {"hc2":{"flowTemp":26.5,"setflowTemp":21,"pumpMod":100}} [error 0]
Setting new thermostat temperature to 20.50 for heating circuit 2 type 0 (0=auto,1=night,2=day,3=holiday)
majdzik84: data is [{"hc2":{"flowTemp":26.5,"setflowTemp":21,"pumpMod":100}}]
[MQTT] Error publishing to home/ems-esp/mixing_data with payload {"hc2":{"flowTemp":26.5,"setflowTemp":21,"pumpMod":100}} [error 0]
Setting new thermostat temperature to 20.0 for heating circuit 2 type 0 (0=auto,1=night,2=day,3=holiday)
majdzik84: data is [{"hc2":{"flowTemp":26.5,"setflowTemp":23,"pumpMod":100}}]
[MQTT] Error publishing to home/ems-esp/mixing_data with payload {"hc2":{"flowTemp":26.5,"setflowTemp":23,"pumpMod":100}} [error 0]
Setting new thermostat temperature to 19.0 for heating circuit 2 type 0 (0=auto,1=night,2=day,3=holiday)
majdzik84: data is [{"hc2":{"flowTemp":26.5,"setflowTemp":23,"pumpMod":100}}]
[MQTT] Error publishing to home/ems-esp/mixing_data with payload {"hc2":{"flowTemp":26.5,"setflowTemp":23,"pumpMod":100}} [error 0]
Setting thermostat mode to off for heating circuit 2
Setting thermostat mode to manual for heating circuit 2
Setting thermostat mode to auto for heating circuit 2
Setting boiler warm water temperature to 52 C
majdzik84: data is [{"hc2":{"flowTemp":26.5,"setflowTemp":23,"pumpMod":100}}]
[MQTT] Error publishing to home/ems-esp/mixing_data with payload {"hc2":{"flowTemp":26.5,"setflowTemp":23,"pumpMod":100}} [error 0]

```

**Comment by majdzik84** [comment] 2020-02-18 12:45
@proddy 
UPDATE
```
Error! Unable to read the EMS bus.
Error! Unable to read the EMS bus.
Error! Unable to read the EMS bus.
Error! Unable to read the EMS bus.
```
After some time I got an error. The gate is blinking - when the LED is working properly, the LED is steady - the RC35 is not working (off).

Restarting the oven and the gate does not result in starting the RC35 - only when I disconnect the gate everything works fine. When it connects the gate, the RC35 is about to shut down again.

**Comment by proddy** [comment] 2020-02-18 15:00
strange. when you say the RC35 does not turn on, do you mean powered on by the EMS lines or just not detected in EMS-ESP?

**Comment by majdzik84** [comment] 2020-02-18 15:46
I mean, RC35 has completely gone out and is not responding (nothing is displayed, no lights are on.) At the same time I see Error in telnet! Unable to read the EMS bus. 

I will add that yesterday I had another situation during testing. On RC35 I had information about errors: (after uploading .bin with a size of 1838kb)

No communication BC10 (A02 816)
external sensor defective (A01 800)
No communication MM10 (A32 816)
No communication UBA/MC10 (A01 816)

**Comment by proddy** [comment] 2020-02-18 17:00
can't think of what could have caused that. Looks like the whole EMS bus crashed and went into some kind of diagnostic/factory mode.

**Comment by proddy** [comment] 2020-02-21 16:53
Hi @majdzik84 I refactored how the MQTT publish works to stage the messages in a queue. It's in b38 so if you have time can you give it a try?

**Comment by majdzik84** [comment] 2020-02-21 19:22
Hi, I will gladly try it when I get home after the weekend. I'll let you know

**Comment by MichaelDvP** [comment] 2020-02-22 15:55
@proddy Very nice work. As a side-effect the web-interface is now responding much better.
But  `MQTT_PUBLISH_WAIT` seems to be a bit to long. There are a lot of messages to send
boiler, thermostat, mixer, sensors, solar, shower, heartbeat, and publish-back on changes. (With non-nested sensors up to 10 more messages) If someone sets publish_time to small values the queue is filled and skips new messages. You have to make sure that publish_time is long enough to send the queue. 
( `MQTT_PUBLISH_WAIT 200` works for me too, but with good wifi connection).

**Comment by proddy** [comment] 2020-02-22 17:03
thanks @MichaelDvP for the feedback. The MQTT queue is set to 20 messages but we can increase it. And also decrease the MQTT_PUBLISH_WAIT. Let's experiment to find the sweet spot.

**Comment by majdzik84** [comment] 2020-02-23 08:24
@Proddy great job. I no longer have reboots when changing temperatures. The latest release seems to be stable for me

I noticed that the boiler temperature again indicates bad values.
the boiler temperature is now 42C and shows 12.5C
![image](https://user-images.githubusercontent.com/31352476/75106541-0fa99100-561e-11ea-96f9-fd79a4d5549f.png)

**Comment by proddy** [comment] 2020-02-23 08:47
arrggh! that infamous boiler temp issue is back again. Every time I fix it for someone it breaks someone else's configuration and I can't figure out the correct logic to use. Could you send me examples of `0x18` and `0x19` again please.

**Comment by majdzik84** [comment] 2020-02-23 12:48
```
(13:35:41) Boiler -> All, type 0x18, telegram: 08 00 18 00 29 01 81 64 23 09 01 25 62 80 00 00 8B 01 62 00 CB 10 2D 48 00 C8 00 02 00 (CRC=F8) #data=25
(13:35:51) Boiler -> All, type 0x18, telegram: 08 00 18 00 29 01 85 64 23 09 01 25 62 80 00 00 8B 01 64 00 CD 10 2D 48 00 C8 00 02 00 (CRC=B8) #data=25
(13:36:41) Boiler -> All, type 0x18, telegram: 08 00 18 00 29 01 91 64 24 09 01 25 62 80 00 00 8B 01 6F 00 DE 10 2D 48 00 C8 00 02 00 (CRC=6E) #data=25
(13:36:48) Boiler -> Me, type 0x18, telegram: 08 0B 18 00 29 01 93 64 24 09 01 25 62 80 00 00 8B 01 71 00 DF 10 2D 48 00 C8 00 02 00 (CRC=3F) #data=25


(13:36:49) Boiler -> Me, type 0x19, telegram: 08 0B 19 00 00 48 01 80 80 00 00 00 00 3F 00 6E EB 04 A2 E3 00 00 00 04 A2 6B 00 6E AE 00 00 (CRC=3D) #data=27
(13:37:21) Boiler -> All, type 0x19, telegram: 08 00 19 00 00 48 01 87 80 00 00 00 00 3F 00 6E EB 04 A2 E3 00 00 00 04 A2 6B 00 6E AE 00 00 (CRC=9D) #data=27
(13:37:50) Boiler -> Me, type 0x19, telegram: 08 0B 19 00 00 48 01 8B 80 00 00 00 00 3F 00 6E EB 04 A2 E4 00 00 00 04 A2 6C 00 6E AE 00 00 (CRC=22) #data=27
(13:39:50) Boiler -> Me, type 0x19, telegram: 08 0B 19 00 00 48 01 86 80 00 00 00 00 3F 00 6E EB 04 A2 E6 00 00 00 04 A2 6E 00 6E AE 00 00 (CRC=A7) #data=27
```

**Comment by proddy** [comment] 2020-02-23 13:21
Ok. I see two values 13.9 degrees (from the x18) and 38.4 (from the x19) and I'm not sure what they mean exactly. Are they
 - Warm Water temperature (which I call boiler temp)
 - Max temperature of boiler?

I'm thinking I should capture both and separate them out. Can you confirm?

**Comment by majdzik84** [comment] 2020-02-23 13:40
To be sure, I send current temperatures, which the furnace shows and telegrams to them.

`(14:39:06) Boiler -> All, type 0x19, telegram: 08 00 19 00 00 41 01 98 80 00 00 00 00 3F 00 6E ED 04 A2 FB 00 00 00 04 A2 83 00 6E B0 00 00 (CRC=A5) #data=27`

Is the temperature 42C?
If so, this is the current boiler temperature, shown on the boiler display

**Comment by proddy** [comment] 2020-02-23 13:48
in your 0x19 I read x0198 = 40.8 C
in your 0x18 I read x008E = 14.2 C

so I'll use 0x19 for the boiler temp. the 14.2 is the warm water temperature. Not sure if its important to show.

**Comment by proddy** [comment] 2020-02-23 14:47
fixed in b41

**Comment by majdzik84** [comment] 2020-02-23 15:14
Thank you very much.

**Comment by majdzik84** [comment] 2020-02-23 16:28
@proddy have the topics thermostat_data changed to thermostat_data1 and thermostat_data2 in b41? is this a mistake?
![image](https://user-images.githubusercontent.com/31352476/75115743-d430b600-5661-11ea-9c46-1c1e206e4da0.png)

**Comment by proddy** [comment] 2020-02-23 16:35
ah yes. I added a new feature `set mqtt_nestedjson`. When off (which is what you have) it has a new behavior where each payload will be sent out seperately. You will need to manually set it back to `on` using `set mqtt_nestjson on`. No need to reboot.

I'll make sure that's its on as default when upgrading from previous releases. Thanks for spotting!

**Comment by MichaelDvP** [comment] 2020-02-24 06:55
Strange thing: In the new b41-build (also the precompiled) the dashboard of the webinterface does not show any data.

**Comment by majdzik84** [comment] 2020-02-24 07:37
I confirm that there is no data in www

**Comment by MichaelDvP** [comment] 2020-02-24 08:21
Found it:  Json and buffer in  
`void MyESP::_sendCustomStatus() {`
are to small. expanding back to `MYESP_JSON_MAXSIZE_LARGE` brings data back.

**Comment by proddy** [comment] 2020-02-24 08:51
fixed in b42. thanks all.

**Comment by proddy** [comment] 2020-02-25 22:05
think the random restart issue has been fixed. if not, please re-open

**Closed by proddy** 2020-02-25 22:05 UTC
Labels: bug
